insert into Companies (id, name, city, street, house_Number, zip_Code)
values  (1, 'Firma1', 'Warszawa', 'ul. Syta ', '25/63', '02-685');
insert into Companies (id, name, city, street, house_Number, zip_Code)
values  (2, 'Firma2', 'Warszawa', 'ul. Dolna ', '4/6', '01-785');
insert into Companies (id, name, city, street, house_Number, zip_Code)
values  (3, 'Firma3', 'Warszawa', 'ul. Dolnaff ', '458/6', '01-785');

insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (1, '146502_8', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Bemowo');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (2, '146503_8', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Białołęka');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (3, '146504_8', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Bielany');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (4, '146505_8', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Mokotów');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (5, '146506_8', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Ochota');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (6, '146507_8', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Praga-Południe');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (7, '146508_8', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Praga-Północ');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (8, '146509_9', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Rembertów');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (9, '146510_9', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Śródmieście');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (10, '146511_9', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Targówek');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (11, '146512_9', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Ursus');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (12, '146513_9', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Ursynów');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (13, '146514_9', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Wawer');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (14, '146515_9', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Wesoła');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (15, '146516_9', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Wilanów');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (16, '146517_9', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Włochy');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (17, '146518_9', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Wola');
insert into Properties (id, TERYT, voivodship, county, gmina, guarter)
values (18, '146519_9', 'mazowieckie', 'm.st. Warszawa', 'm.st. Warszawa', 'Żoliborz');